/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

/**
 *
 * @author Tomas
 */
public class Seleccion_productos_viaje extends javax.swing.JFrame {

    /**
     * Creates new form Seleccion_productos_viaje
     */
    public Seleccion_productos_viaje() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCheckBox_CocaCola = new javax.swing.JCheckBox();
        jCheckBoxDoritos = new javax.swing.JCheckBox();
        jCheckBox_DeTodito = new javax.swing.JCheckBox();
        jCheckBox_Sprite = new javax.swing.JCheckBox();
        jCheckBox_CrispetasDulces = new javax.swing.JCheckBox();
        jCheckBox_CrispetasSaladas = new javax.swing.JCheckBox();
        jCheckBox_Jet = new javax.swing.JCheckBox();
        jCheckBox_Speed = new javax.swing.JCheckBox();
        jCheckBox_Colombiana = new javax.swing.JCheckBox();
        jCheckBox_Tostacos = new javax.swing.JCheckBox();
        jCheckBox_Choclitos = new javax.swing.JCheckBox();
        jCheckBox_Manzana = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        txtCosto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        btnContinuar = new javax.swing.JButton();
        btnCalcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        jLabel1.setText("Selección de Productos: ");

        jLabel2.setText("Los productos a escoger varían dependiendo del paquete. ");

        jCheckBox_CocaCola.setText("Coca-Cola 3L");
        jCheckBox_CocaCola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_CocaColaActionPerformed(evt);
            }
        });

        jCheckBoxDoritos.setText("Doritos Grande");

        jCheckBox_DeTodito.setText("DeTodito Grande");

        jCheckBox_Sprite.setText("Sprite 3L");

        jCheckBox_CrispetasDulces.setText("Paquete Crispetas Dulces Grande ");

        jCheckBox_CrispetasSaladas.setText("Paquete Crispetas Saladas Grande ");

        jCheckBox_Jet.setText("Chocolatina Jet Grande ");

        jCheckBox_Speed.setText("SpeedMax 1L ");

        jCheckBox_Colombiana.setText("Colombiana 2.5L ");

        jCheckBox_Tostacos.setText("Tostacos Grande  ");

        jCheckBox_Choclitos.setText("Choclitos Grande  ");

        jCheckBox_Manzana.setText("Gaseosa Manzana 2.5L ");
        jCheckBox_Manzana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_ManzanaActionPerformed(evt);
            }
        });

        jLabel3.setText("Costo total:");

        txtCosto.setEditable(false);
        txtCosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCostoActionPerformed(evt);
            }
        });

        jLabel4.setText("El mínimo de dinero a gastar en este paquete es: 35.000 ");

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnContinuar.setText("Continuar");
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(174, 174, 174))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(152, 152, 152))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox_CrispetasSaladas)
                            .addComponent(jCheckBox_CrispetasDulces)
                            .addComponent(jCheckBox_Sprite, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox_DeTodito)
                            .addComponent(jCheckBoxDoritos)
                            .addComponent(jCheckBox_CocaCola))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox_Jet)
                            .addComponent(jCheckBox_Speed)
                            .addComponent(jCheckBox_Colombiana)
                            .addComponent(jCheckBox_Tostacos)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jCheckBox_Manzana, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jCheckBox_Choclitos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCalcular)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(btnVolver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnContinuar)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox_CocaCola)
                    .addComponent(jCheckBox_Manzana))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxDoritos)
                    .addComponent(jCheckBox_Choclitos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox_DeTodito)
                    .addComponent(jCheckBox_Tostacos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox_Sprite)
                    .addComponent(jCheckBox_Colombiana))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox_CrispetasDulces)
                    .addComponent(jCheckBox_Speed))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox_CrispetasSaladas)
                    .addComponent(jCheckBox_Jet))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCalcular)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnVolver)
                        .addComponent(btnContinuar)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox_ManzanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_ManzanaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_ManzanaActionPerformed

    private void txtCostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCostoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCostoActionPerformed

    int total = 0;
    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
    total = 0;
    
    if (jCheckBox_CocaCola.isSelected()){
        total += 10000;
    }
    if (jCheckBoxDoritos.isSelected()){
        total += 10000;
    }
    if (jCheckBox_DeTodito.isSelected()){
        total += 10000;
    }
    if (jCheckBox_Sprite.isSelected()){
        total += 10000;
    }
    if (jCheckBox_CrispetasDulces.isSelected()){
        total += 8000;
    }
    if (jCheckBox_CrispetasSaladas.isSelected()){
        total += 8000;
    }
    if (jCheckBox_Manzana.isSelected()){
        total += 9000;
    }
    if (jCheckBox_Choclitos.isSelected()){
        total += 10000;
    }
    if (jCheckBox_Tostacos.isSelected()){
        total += 10000;
    }
    if (jCheckBox_Colombiana.isSelected()){
        total += 9000;
    }
    if (jCheckBox_Speed.isSelected()){
        total += 6000;
    }
    if (jCheckBox_Jet.isSelected()){
        total += 6000;
    }
    txtCosto.setText(String.valueOf(total));
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void jCheckBox_CocaColaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_CocaColaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_CocaColaActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
    Paquetes_disponibles paquetes = new Paquetes_disponibles();
    paquetes.setVisible(true);
    dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
    if (total  >= 35000){
    Añadir_tour tour = new Añadir_tour();
    tour.setVisible(true);
    dispose();
    }else{
    }
    
    }//GEN-LAST:event_btnContinuarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Seleccion_productos_viaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Seleccion_productos_viaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Seleccion_productos_viaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Seleccion_productos_viaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Seleccion_productos_viaje().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnContinuar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JCheckBox jCheckBoxDoritos;
    private javax.swing.JCheckBox jCheckBox_Choclitos;
    private javax.swing.JCheckBox jCheckBox_CocaCola;
    private javax.swing.JCheckBox jCheckBox_Colombiana;
    private javax.swing.JCheckBox jCheckBox_CrispetasDulces;
    private javax.swing.JCheckBox jCheckBox_CrispetasSaladas;
    private javax.swing.JCheckBox jCheckBox_DeTodito;
    private javax.swing.JCheckBox jCheckBox_Jet;
    private javax.swing.JCheckBox jCheckBox_Manzana;
    private javax.swing.JCheckBox jCheckBox_Speed;
    private javax.swing.JCheckBox jCheckBox_Sprite;
    private javax.swing.JCheckBox jCheckBox_Tostacos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JTextField txtCosto;
    // End of variables declaration//GEN-END:variables
}
