/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

/**
 *
 * @author Tomas
 */
public class seleccion_productos extends javax.swing.JFrame {

    /**
     * Creates new form seleccion_productos
     */
    public seleccion_productos() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCheckBox_aguardienteL = new javax.swing.JCheckBox();
        jCheckBox_ronLcaldas = new javax.swing.JCheckBox();
        jCheckBox_ronLmedellin = new javax.swing.JCheckBox();
        jCheckBox_packaguila = new javax.swing.JCheckBox();
        jCheckBox_packpocker = new javax.swing.JCheckBox();
        jCheckBox_gatorade = new javax.swing.JCheckBox();
        jCheckBox_agua = new javax.swing.JCheckBox();
        jCheckBox_smirnoff = new javax.swing.JCheckBox();
        jCheckBox_buchanans = new javax.swing.JCheckBox();
        jCheckBox_papaslimon = new javax.swing.JCheckBox();
        jCheckBox_rosquillas = new javax.swing.JCheckBox();
        jCheckBox_papasnaturales = new javax.swing.JCheckBox();
        txtCosto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        btnContinuar = new javax.swing.JButton();
        btnCalcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        jLabel1.setText("Seleccion de Productos");

        jLabel2.setText("Los productos a escoger varían dependiendo del paquete.");

        jCheckBox_aguardienteL.setText("Litro de aguardiente");
        jCheckBox_aguardienteL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_aguardienteLActionPerformed(evt);
            }
        });

        jCheckBox_ronLcaldas.setText("Litro de Ron viejo Caldas ");

        jCheckBox_ronLmedellin.setText("Litro de Ron Medellín ");

        jCheckBox_packaguila.setText("Six pack cerveza aguila light ");

        jCheckBox_packpocker.setText("Six pack cerveza poker  ");

        jCheckBox_gatorade.setText("Gatorade pequeño ");

        jCheckBox_agua.setText("Botella de agua");
        jCheckBox_agua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_aguaActionPerformed(evt);
            }
        });

        jCheckBox_smirnoff.setText("Botella SmirnOff ");

        jCheckBox_buchanans.setText("Buchanans 1000 años ");

        jCheckBox_papaslimon.setText("Papitas Limón Grandes ");

        jCheckBox_rosquillas.setText("Rosquillas Grandes ");

        jCheckBox_papasnaturales.setText("Papitas Naturales Grandes ");

        txtCosto.setEditable(false);
        txtCosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCostoActionPerformed(evt);
            }
        });

        jLabel3.setText("Costo total:");

        jLabel4.setText("El mínimo de dinero a gastar en este paquete es: 100.000 ");

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnContinuar.setText("Continuar");
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox_aguardienteL)
                                    .addComponent(jCheckBox_ronLcaldas, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCheckBox_ronLmedellin)
                                    .addComponent(jCheckBox_packaguila)
                                    .addComponent(jCheckBox_packpocker)
                                    .addComponent(jCheckBox_gatorade))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox_smirnoff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCheckBox_buchanans, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCheckBox_agua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCheckBox_papaslimon)
                                            .addComponent(jCheckBox_rosquillas, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jCheckBox_papasnaturales))
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel4)
                        .addGap(68, 68, 68)
                        .addComponent(btnVolver)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnContinuar)))
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(13, 13, 13)
                        .addComponent(txtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(232, 232, 232))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCalcular)
                        .addGap(266, 266, 266))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox_aguardienteL)
                    .addComponent(jCheckBox_agua))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox_ronLcaldas)
                    .addComponent(jCheckBox_smirnoff))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox_ronLmedellin)
                    .addComponent(jCheckBox_buchanans))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox_packaguila)
                    .addComponent(jCheckBox_papaslimon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox_packpocker)
                    .addComponent(jCheckBox_rosquillas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox_gatorade)
                    .addComponent(jCheckBox_papasnaturales))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCalcular)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel4))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnVolver)
                        .addComponent(btnContinuar)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox_aguardienteLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_aguardienteLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_aguardienteLActionPerformed

    private void txtCostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCostoActionPerformed

    }//GEN-LAST:event_txtCostoActionPerformed

    private void jCheckBox_aguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_aguaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_aguaActionPerformed

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        Formulario f = new Formulario();
        f.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnContinuarActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
    int total = 0;
    
    if (jCheckBox_aguardienteL.isSelected()){
        total += 45000;
    }
    if (jCheckBox_ronLcaldas.isSelected()){
        total += 55000;
    }
    if (jCheckBox_ronLmedellin.isSelected()){
        total += 50000;
    }
    if (jCheckBox_packaguila.isSelected()){
        total += 22000;
    }
    if (jCheckBox_packpocker.isSelected()){
        total += 20000;
    }
    if (jCheckBox_gatorade.isSelected()){
        total += 7000;
    }
    if (jCheckBox_agua.isSelected()){
        total += 4000;
    }
    if (jCheckBox_smirnoff.isSelected()){
        total += 50000;
    }
    if (jCheckBox_buchanans.isSelected()){
        total += 100000;
    }
    if (jCheckBox_papaslimon.isSelected()){
        total += 12000;
    }
    if (jCheckBox_rosquillas.isSelected()){
        total += 8000;
    }
    if (jCheckBox_papasnaturales.isSelected()){
        total += 10000;
    }
    txtCosto.setText(String.valueOf(total));
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(seleccion_productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(seleccion_productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(seleccion_productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(seleccion_productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new seleccion_productos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnContinuar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JCheckBox jCheckBox_agua;
    private javax.swing.JCheckBox jCheckBox_aguardienteL;
    private javax.swing.JCheckBox jCheckBox_buchanans;
    private javax.swing.JCheckBox jCheckBox_gatorade;
    private javax.swing.JCheckBox jCheckBox_packaguila;
    private javax.swing.JCheckBox jCheckBox_packpocker;
    private javax.swing.JCheckBox jCheckBox_papaslimon;
    private javax.swing.JCheckBox jCheckBox_papasnaturales;
    private javax.swing.JCheckBox jCheckBox_ronLcaldas;
    private javax.swing.JCheckBox jCheckBox_ronLmedellin;
    private javax.swing.JCheckBox jCheckBox_rosquillas;
    private javax.swing.JCheckBox jCheckBox_smirnoff;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtCosto;
    // End of variables declaration//GEN-END:variables
}
