/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package misproyectos.proyecto_chivas;

/**
 *
 * @author Tomas
 */
public class Viajes_disponibles extends javax.swing.JFrame {

    /**
     * Creates new form Viajes_disponibles
     */
    public Viajes_disponibles() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frameError_nocupos = new javax.swing.JFrame();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnVolvermenu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaViajes = new javax.swing.JTable();
        btnVolver = new javax.swing.JButton();
        btnViaje1 = new javax.swing.JButton();
        btnViaje2 = new javax.swing.JButton();
        bntViaje3 = new javax.swing.JButton();

        frameError_nocupos.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel4.setText("ERROR");

        jLabel5.setText("No hay cupos disponibles para este servicio ");

        btnVolvermenu.setText("Volver al menu principal");
        btnVolvermenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolvermenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frameError_nocuposLayout = new javax.swing.GroupLayout(frameError_nocupos.getContentPane());
        frameError_nocupos.getContentPane().setLayout(frameError_nocuposLayout);
        frameError_nocuposLayout.setHorizontalGroup(
            frameError_nocuposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameError_nocuposLayout.createSequentialGroup()
                .addGroup(frameError_nocuposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frameError_nocuposLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel4))
                    .addGroup(frameError_nocuposLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel5))
                    .addGroup(frameError_nocuposLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(btnVolvermenu)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        frameError_nocuposLayout.setVerticalGroup(
            frameError_nocuposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameError_nocuposLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(btnVolvermenu, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        jLabel1.setText("Viajes disponibles:");

        jLabel2.setText("Se recuerda al usuario que si se quiere viajar con menor de edad, se le debe registrar un acudiente.");

        jLabel3.setText("El precio no incluye el paquete/tour extra en caso de seleccionarlos. ");

        TablaViajes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, "30/30", "24/10/2023", "50.000", "Medellín/La Ceja"},
                {null, null, "10:00-17:00", null, null},
                {null, null, null, null, null},
                {null, "40/60", "31/10/2023", "50.000", "Medellín/Marinilla"},
                {null, null, "8:00 - 06:00", null, null},
                {null, null, null, null, null},
                {null, "7/20", "15/10/2023", "50.000", "Medellín/Rionegro"},
                {null, null, "10:00 - 16:00", null, null}
            },
            new String [] {
                "IMAGEN", "AFORO", "HORARIO", "PRECIO", "SALIDA/DESTINO"
            }
        ));
        jScrollPane1.setViewportView(TablaViajes);

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnViaje1.setText("SELECCIONAR");
        btnViaje1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViaje1ActionPerformed(evt);
            }
        });

        btnViaje2.setText("SELECCIONAR");
        btnViaje2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViaje2ActionPerformed(evt);
            }
        });

        bntViaje3.setText("SELECCIONAR");
        bntViaje3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntViaje3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnViaje1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnViaje2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bntViaje3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 8, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(btnViaje1)
                        .addGap(27, 27, 27)
                        .addComponent(btnViaje2)
                        .addGap(29, 29, 29)
                        .addComponent(bntViaje3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViaje1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViaje1ActionPerformed
        Object valor = TablaViajes.getValueAt(1, 1);
        String texto = valor.toString();
        String[] numeros = texto.split("/");
        
        int personas = Integer.parseInt(numeros[0]);
        int maximas = Integer.parseInt(numeros[1]);
        
        if (personas < maximas){
            Añadir_paquete añadir = new Añadir_paquete();
            añadir.setVisible(true);
            dispose();
        }else{
            frameError_nocupos.setVisible(true);
            frameError_nocupos.setLocationRelativeTo(null);
            frameError_nocupos.setSize(400,320);
        }
        
    }//GEN-LAST:event_btnViaje1ActionPerformed

    private void btnVolvermenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolvermenuActionPerformed
        PaginaPrincipal a = new PaginaPrincipal();
        a.setVisible(true);
        frameError_nocupos.setVisible(false);
        dispose();
    }//GEN-LAST:event_btnVolvermenuActionPerformed

    private void btnViaje2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViaje2ActionPerformed
    Object valor = TablaViajes.getValueAt(4, 1);
        String texto = valor.toString();
        String[] numeros = texto.split("/");
        
        int personas = Integer.parseInt(numeros[0]);
        int maximas = Integer.parseInt(numeros[1]);
        
        if (personas < maximas){
            Añadir_paquete añadir = new Añadir_paquete();
            añadir.setVisible(true);
            dispose();
        }else{
            frameError_nocupos.setVisible(true);
            frameError_nocupos.setLocationRelativeTo(null);
            frameError_nocupos.setSize(400,320);
        }
    }//GEN-LAST:event_btnViaje2ActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
    PaginaPrincipal a = new PaginaPrincipal();
    a.setVisible(true);
    dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void bntViaje3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntViaje3ActionPerformed
    Object valor = TablaViajes.getValueAt(7, 1);
        String texto = valor.toString();
        String[] numeros = texto.split("/");
        
        int personas = Integer.parseInt(numeros[0]);
        int maximas = Integer.parseInt(numeros[1]);
        
        if (personas < maximas){
            Añadir_paquete añadir = new Añadir_paquete();
            añadir.setVisible(true);
            dispose();
        }else{
            frameError_nocupos.setVisible(true);
            frameError_nocupos.setLocationRelativeTo(null);
            frameError_nocupos.setSize(400,320);
        }
    }//GEN-LAST:event_bntViaje3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Viajes_disponibles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Viajes_disponibles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Viajes_disponibles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Viajes_disponibles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Viajes_disponibles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaViajes;
    private javax.swing.JButton bntViaje3;
    private javax.swing.JButton btnViaje1;
    private javax.swing.JButton btnViaje2;
    private javax.swing.JButton btnVolver;
    private javax.swing.JButton btnVolvermenu;
    private javax.swing.JFrame frameError_nocupos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
